---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MetaboDynamics

<!-- badges: start -->
<!-- badges: end -->

MetaboDynamics provides a framework of Bayesian models for robust and easy
analysis of longitudinal Metabolomics Data. It takes concentration tables as input an provides robust estimation of mean concentrations, functional enrichment
analysis employing the KEGG database and comparison of dynamic clusters of 
different biological conditions.

## Installation

You can install the development version of MetaboDynamics from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("KatjaDanielzik/MetaboDynamics")
```

## Overview
this should describe the main components of the package and can point to the
vignettes in case of a more complex package
Describe also how the pacakge fits into the ecosystem of its target domain.


## Workflow & output
graphical abstract of workflow with data input and example outputs
